### ISSUE TITLE
Config database

### ISSUE THREAD

**Issue by NguyenMinhDuc163** [dpbL5/moneymanager#10]
![Screenshot 2024-11-07 134119](https://github.com/user-attachments/assets/0542350a-9c6e-4b41-a159-f3110f00720e)

**Comment by dpbL5** [comment]
Tham khảo anh ơi

**Comment by NguyenMinhDuc163** [comment]
K xoá của password luôn, trước ít kinh nghiêm cấu hình nhu vậy thôi giờ làm kiểu khác nó tối ưu hơn

**Comment by NguyenMinhDuc163** [comment]
Nếu cấu hình như thế này sẽ hay hơn dùng Factory design  pattem và single design pattern, sau nếu không muốn dùng mysql thì thay bằng database sẽ đơn giản chi phí sửa là ít nhất, với sẽ không để lộ user password database
[https://gist.github.com/NguyenMinhDuc163/9e7d460ef8765e36d91849ad2e8c53da](url)

**Comment by dpbL5** [comment]
Anh này troll quá troll

**Comment by NguyenMinhDuc163** [comment]
Đây uy tín [Tại đây](https://gist.github.com/NguyenMinhDuc163/9e7d460ef8765e36d91849ad2e8c53da)
